kind: Deployment
apiVersion: apps/v1
metadata:
  name: psrestapi-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: psrestapi
  template:
    metadata:
      name: psrestapi
      labels:
        app: psrestapi
        env: dev
    spec:
      containers:
      - name: psrestapi
        image: test01cntrgtr.azurecr.io/psrestapi:0.2.0
        resources:
          limits:
            memory: "300Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 4000
      imagePullSecrets:
      - name: acr-auth
---
kind: Service
apiVersion: v1
metadata:
  name: psrestapi
  labels:
    name: psrestapi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: psrestapi

