node {
  def acr = 'devopscampdemo.azurecr.io'
  def appName = 'gceme'
  def imageTag = "${acr}/${appName}"

  checkout scm
  
 stage('Build the Image and Push to Azure Container Registry')          {
   app = docker.build("${imageTag}")
   withDockerRegistry([credentialsId: 'acr_auth', url: "https://${acr}"]) {
                app.push("${env.BRANCH_NAME}.${env.BUILD_NUMBER}")
                }
        }
}
