node {
  def acr = 'devopscampdemo.azurecr.io'
  def appName = 'gceme'
  def feSvcName = "${appName}-frontend"
  def imageTag = "${acr}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"

  checkout scm
  
 stage('Build the Image and Push to Azure Container Registry')          {
   app = docker.build("${imageTag}")
   withDockerRegistry([credentialsId: 'acr_credentials', url: "${acr}"]) {
                app.push("${imageTag}")
                app.push('latest')
                }
        }
}
