node {
  def acr = 'devopscampdemo.azurecr.io'
  def appName = 'gceme'
  def feSvcName = "${appName}-frontend"
  def imageTag = "${acr}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"

  checkout scm

  stage 'Build image'
  sh("docker build -t ${imageTag} .")

  stage 'Run Go tests'
  sh("docker run ${imageTag} go test")

  stage 'Push image to registry'
  sh("gcloud docker -- push ${imageTag}")

}
